# Generated by Django 4.2.4 on 2023-10-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='resume',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
